# Generated by Django 2.1.4 on 2019-04-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
